# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarketCurly' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarketCurly
pod 'ExpyTableView'
pod 'Alamofire', '~> 5.2'
pod 'Kingfisher', '~> 6.0'

  target 'MarketCurlyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarketCurlyUITests' do
    # Pods for testing

  end

end
